### ISSUE TITLE
Testnet status monitor

### ISSUE THREAD

**Issue by anisim0v** [copperbits/TON#12]
Hi! I made a simple Telegram channel that displays if the testnet is up or down.
https://t.me/testnetstatus

**Comment by anisim0v** [comment]
And it will notify about the config file (https://test.ton.org/ton-lite-client-test1.config.json) changes

**Comment by skywinder** [comment]
I'd be more than happy to merge a PR adding this note, it seems like it would be useful for sure 👍

**Comment by skywinder** [comment]
I would happy to merge!
as well as in https://github.com/copperbits/awesome-ton - the universal list of different kind of tools.

**Comment by skywinder** [comment]
Hey, @anisim0v  thanks for this feature. let me know if you are going to update it. 
p.s.
Is your bot open source? I would like to make a reference to this project as well to consolidate all the information in one place.
