### ISSUE TITLE
Put your proposals / feature requests here ⤵️

### ISSUE THREAD

**Issue by skywinder** [copperbits/TON#2]
- [ ] Need help with building a light client?
- [ ] How to write a smart contract?
- [ ] How to deploy it?
- [ ] How to use the faucet for test Gram's?

## Feel free to ask everything below!

**Comment by hisac** [comment]
I was able to compile the ton lite client on OSX  High Sierra. The test client works fine but a the time I want to create a new wallet I get this error: 
$ crypto/fift new-wallet.fif 
**[ 1][t 0][1559536592.549882889][fift-main.cpp:147] Error interpreting standard preamble file `Fift.fif`: cannot locate file `Fift.fif`
Check that correct include path is set by -I or by FIFTPATH environment variable, or disable standard preamble by -n.**

If I do $ crypto/fift -n by itself fift works, I know it was compiled correctly.
I see Is a PATH related issue, tried different things but no luck.

**Comment by morandalex** [comment]
I had the same issue . I solved giving the right path of the fift and asm library.


./crypto/fift ( from te build folder )
-I/no/build/directory/but/lite/client/directory/crypto/fift/lib
file that you want to compile

example
` home/user/build$ sudo  ./crypto/fift  -I/home/user/lite-client/crypto/fift/lib  new-wallet.fif `

**Comment by skywinder** [comment]
@morandalex which version of client are you using? Consider updating from https://github.com/ton-blockchain/ton/

@hisac I miss your comment, if it's still actual, please make a separate issue for that. I will try to help with this

**Comment by skywinder** [comment]
Closing this issue, since there is a lot of new information comes from the official ton group.
Please, add all the future references to https://github.com/copperbits/awesome-ton
