### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tot1342** [copperbits/TON#4]
I have problem with code when i do cmake --build . --target test-lite-client
OS ubuntu 18.4
compiler g++5 and clang8
`
/home/rasta/lite-client/tdutils/td/utils/tests.cpp:37:59: error: use of undeclared identifier 'sha256'
    auto hash = PSTRING() << format::as_hex_dump<0>(Slice(sha256(result)));
1 error generated.
tdutils/CMakeFiles/tdutils.dir/build.make:1310: recipe for target 'tdutils/CMakeFiles/tdutils.dir/td/utils/tests.cpp.o' failed
make[3]: *** [tdutils/CMakeFiles/tdutils.dir/td/utils/tests.cpp.o] Error 1
CMakeFiles/Makefile2:1938: recipe for target 'tdutils/CMakeFiles/tdutils.dir/all' failed
make[2]: *** [tdutils/CMakeFiles/tdutils.dir/all] Error 2
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/test-lite-client.dir/rule' failed
make[1]: *** [CMakeFiles/test-lite-client.dir/rule] Error 2
Makefile:164: recipe for target 'test-lite-client' failed
make: *** [test-lite-client] Error 2
`
and if I delet this function (sha256), then I have problen in the other place

/home/rasta/lite-client/crypto/vm/tonops.cpp:82:7: error: no member named 'Ed25519' in namespace 'td'
  td::Ed25519::PublicKey pub_key{td::Slice{key, 32}};
  ~~~~^
1 error generated.
crypto/CMakeFiles/ton_crypto.dir/build.make:638: recipe for target 'crypto/CMakeFiles/ton_crypto.dir/vm/tonops.cpp.o' failed
make[3]: *** [crypto/CMakeFiles/ton_crypto.dir/vm/tonops.cpp.o] Error 1
CMakeFiles/Makefile2:3141: recipe for target 'crypto/CMakeFiles/ton_crypto.dir/all' failed
make[2]: *** [crypto/CMakeFiles/ton_crypto.dir/all] Error 2
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/test-lite-client.dir/rule' failed
make[1]: *** [CMakeFiles/test-lite-client.dir/rule] Error 2
Makefile:164: recipe for target 'test-lite-client' failed
make: *** [test-lite-client] Error 2

**Comment by tot1342** [comment]
Install zlib1g-dev halped me

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still any questions 👍
